baseURL = "https://gauravaror.github.io/"
languageCode = "en-us"
title = "Gaurav Arora"
theme = "beautifulhugo"
googleAnalytics = "UA-153642264"
[[author]]
  name = "Dean Attali"
  email = "dean@attalitech.com"
  facebook = "deanattali"
  github = "daattali"
  twitter = "daattali"
  linkedin = "pub/dean-attali/8/946/143"
  stackoverflow = "users/3943160/daattali"
  calendly = "attalitech/meeting"

