baseURL = "https://gauravaror.github.io/"
languageCode = "en-us"
title = "Gaurav Arora"
theme = "beautifulhugo"
googleAnalytics = "UA-153642264"
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
[[author]]
  name = "Gaurav Arora"
  email = "gauravarora.daiict@gmail.com"

[[menu.main]]
    name = "Blog"
    weight = 130
    url = "/"

[[menu.main]]
    name = "CV"
    weight = 150
    url = "/gaurav-cv.pdf"

