baseURL = "https://gauravaror.github.io/"
languageCode = "en-us"
title = "Gaurav Arora"
theme = "beautifulhugo"
googleAnalytics = "UA-153642264"
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
[[author]]
  name = "Gaurav Arora"
  email = "gauravarora.daiict@gmail.com"
